Add interface type filters to ros2 interface package
ros2/ros2cli pull request #765
Opened 2022-09-21 17:40 UTC by DLu

Seemed like it was missing.

2022-11-03 13:49 UTC, clalancette requested changes

2022-11-03 13:49 UTC, clalancette commented on ros2interface/ros2interface/verb/package.py
> +                        continue
I don't feel like this is the right way to filter here.

In particular, while we almost certainly aren't going to change the prefix for `msg`, `srv`, and `action`, we also have dedicated functions for getting this information.  Thus, I think we should refactor this whole block to be something like:

```
interfaces = []
if not args.only_msgs and not args.only_srvs and not args.only_actions:
    interfaces = get_interfaces([args.package_name])
else:
    if args.only_msgs:
        interfaces += get_message_interfaces([args.package_name])
    if args.only_srvs:
        interfaces += get_service_interfaces([args.package_name])
    if args.only_actions:
        interfaces += get_action_interfaces([args.package_name])

for package_name in sorted(interfaces):
    for interface_name in interfaces[package_name]:
        print(f'{package_name}/{interface_name}')

```

2023-02-01 20:07 UTC, clalancette requested changes
A couple more minor things to fix, then I think this will be ready for CI.

2023-02-01 20:07 UTC, clalancette commented on ros2interface/ros2interface/verb/package.py
> +import collections
You need whitespace both before and after this to pass flake8.

```suggestion

import collections

```

2023-02-01 20:07 UTC, clalancette commented on ros2interface/test/test_cli.py
> +        assert all(interface in output_lines for interface in some_services_from_test_msgs)
It is probably overkill, but I'd feel a little better about this if we had 3 tests, one for each of `-s`, `-m`, and `-a`.  Also, I'm concerned about a 2 second timeout for the shutdown, particularly on Windows; I'll suggest 5 seconds instead.

2023-02-03 01:37 UTC, fujitatomoya reviewed
lgtm with @clalancette comment addressed

2023-05-19 19:06 UTC, clalancette approved these changes

2023-05-19 19:07 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18768)](http://ci.ros2.org/job/ci_linux/18768/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13291)](http://ci.ros2.org/job/ci_linux-aarch64/13291/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19509)](http://ci.ros2.org/job/ci_windows/19509/)

2023-05-19 20:15 UTC, merged