Updated wording in list.py
ros2/ros2cli pull request #775
Opened 2022-11-07 20:59 UTC by MikeWrock

Signed-off-by: Michael Wrock

Updated wording for the warning displayed when multiple nodes share the same name

2022-11-07 21:20 UTC, fujitatomoya approved these changes

2022-11-08 13:23 UTC, clalancette requested changes

2022-11-08 13:23 UTC, clalancette commented on ros2node/ros2node/verb/list.py
> +                      'name, this can have unintended side effects.', file=sys.stderr)
If we are going to be pedantic about the wording:

```suggestion
                print('WARNING: Be aware that there are nodes in the graph that share an exact '
                      'name, which can have unintended side effects.', file=sys.stderr)
```

2022-11-08 16:49 UTC, clalancette approved these changes

2022-11-08 16:50 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17608)](http://ci.ros2.org/job/ci_linux/17608/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12150)](http://ci.ros2.org/job/ci_linux-aarch64/12150/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18178)](http://ci.ros2.org/job/ci_windows/18178/)

2022-11-08 21:48 UTC, merged