Replace unmaintained `netifaces` library to avoid local wheel builds
ros2/ros2cli pull request #875
Opened 2024-01-10 20:45 UTC by lalten

[netifaces](https://github.com/al45tair/netifaces) is unmaintained: https://github.com/al45tair/netifaces/issues/78.
It does not provide official prebuilt wheels for Python > 3.9: https://pypi.org/project/netifaces/#files

There is an active fork, https://pypi.org/project/netifaces-plus, but it does not provide a python3-netifaces-plus (apt) package.

https://github.com/pydron/ifaddr is an alternative (which does come as `python3-ifaddr`) but the interface is a little different.

The reason I'm making this change is that we want to upgrade to a Python>3.9 but not provide a compiler inside our CI container (Unrelated to this PR, but we're using Bazel with a standalone hermetic compiler toolchain and https://github.com/mvukov/rules_ros2). Not having a host compiler for Python wheel builds makes it more difficult to build netifaces.

There are only two `netifaces` usages in ros2cli:

**LocalXMLRPCServer**
It just needs a list of available IPv4s (only `AF_INET`, no `AF_INET6`). ifaddr can provide a one-line replacement for the `get_local_ipaddrs()` function:
```
❯ ipython3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.31.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import netifaces, ifaddr

In [2]: def get_local_ipaddrs():
   ...:     iplist = []
   ...:     interfaces = netifaces.interfaces()
   ...:     for interface in interfaces:
   ...:         addrs = netifaces.ifaddresses(interface)
   ...:         if netifaces.AF_INET in addrs.keys():
   ...:             for value in addrs[netifaces.AF_INET]:
   ...:                 iplist.append(value['addr'])
   ...:     return iplist
   ...:

In [3]: get_local_ipaddrs()
Out[3]: ['127.0.0.1', '172.16.103.157', '172.17.0.1']

In [4]: [ip.ip for adptr in ifaddr.get_adapters() for ip in adptr.ips if ip.is_IPv4]
Out[4]: ['127.0.0.1', '172.16.103.157', '172.17.0.1']
```

**NetworkAwareNode**
It must restart if network interfaces change. Currently it's checking for changes by comparing a (default)dict containing netiface's data.
In my ifaddr replacement it will instead compare a set of repr-strings that contain all data ifaddr provides.
```
❯ ipython3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.31.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import netifaces, ifaddr, functools

In [2]: from collections import defaultdict

In [3]: def get_interfaces_ip_addresses():
   ...:     addresses_by_interfaces = defaultdict(functools.partial(defaultdict, set))
   ...:     for interface_name in netifaces.interfaces():
   ...:         for kind, info_list in netifaces.ifaddresses(interface_name).items():
   ...:             for info in info_list:
   ...:                 addresses_by_interfaces[kind][interface_name].add(info['addr'])
   ...:     print(f'Addresses by interfaces: {addresses_by_interfaces}')
   ...:     return addresses_by_interfaces
   ...:

In [4]: get_interfaces_ip_addresses()
Addresses by interfaces: defaultdict(..., {17: defaultdict(<class 'set'>, {'lo': {'00:00:00:00:00:00'}, 'enp5s0': {'d4:5d:64:57:12:27'}, 'docker0': {'02:42:01:8e:b3:0b'}}), 2: defaultdict(<class 'set'>, {'lo': {'127.0.0.1'}, 'enp5s0': {'172.16.103.157'}, 'docker0': {'172.17.0.1'}}), 10: defaultdict(<class 'set'>, {'lo': {'::1'}, 'enp5s0': {'fe80::5c44:433c:8cf8:a7c7%enp5s0'}, 'docker0': {'fe80::42:1ff:fe8e:b30b%docker0'}})})
Out[4]:
defaultdict(functools.partial(<class 'collections.defaultdict'>, <class 'set'>),
            {17: defaultdict(set,
                         {'lo': {'00:00:00:00:00:00'},
                          'enp5s0': {'d4:5d:64:xx:xx:xx'},
                          'docker0': {'02:42:01:8e:b3:0b'}}),
             2: defaultdict(set,
                         {'lo': {'127.0.0.1'},
                          'enp5s0': {'172.16.103.157'},
                          'docker0': {'172.17.0.1'}}),
             10: defaultdict(set,
                         {'lo': {'::1'},
                          'enp5s0': {'fe80::5c44:433c:8cf8:a7c7%enp5s0'},
                          'docker0': {'fe80::42:1ff:fe8e:b30b%docker0'}})})

In [5]: {repr(a) for a in ifaddr.get_adapters()}
Out[5]:
{"Adapter(name='docker0', nice_name='docker0', ips=[IP(ip='172.17.0.1', network_prefix=16, nice_name='docker0'), IP(ip=('fe80::42:1ff:fe8e:b30b', 0, 3), network_prefix=64, nice_name='docker0')], index=3)",
 "Adapter(name='enp5s0', nice_name='enp5s0', ips=[IP(ip='172.16.103.157', network_prefix=22, nice_name='enp5s0'), IP(ip=('fe80::5c44:433c:8cf8:a7c7', 0, 2), network_prefix=64, nice_name='enp5s0')], index=2)",
 "Adapter(name='lo', nice_name='lo', ips=[IP(ip='127.0.0.1', network_prefix=8, nice_name='lo'), IP(ip=('::1', 0, 0), network_prefix=128, nice_name='lo')], index=1)"}
```
There is one slight behavior change here:
ifaddr also only reports information about AF_INET and AF_INET6. netifaces includes other network families as well. In my example it includes AF_PACKET (MAC addresses) but I think it would also report for e.g. Socketcan, Bluetooth, ... interfaces.
I am not sure network interfaces like these are really officially supported. It is probably fine to change this to only watch for IPv4, IPv6, interface name, netmask changes.

2024-01-10 20:51 UTC, clalancette requested changes
So 2 years ago, in #687, I switched `ros2doctor` from using `python3-ifcfg` to using `python3-psutil` for network configuration.  If it is possible, I think we should prefer to switch to using `python3-psutil` here to reduce our dependencies.  @lalten can you take a look at the `python3-psutil` APIs and see if we can accomplish the same thing?

2024-01-10 21:10 UTC, lalten commented
> So 2 years ago, in #687, I switched `ros2doctor` from using `python3-ifcfg` to using `python3-psutil` for network configuration. If it is possible, I think we should prefer to switch to using `python3-psutil` here to reduce our dependencies. @lalten can you take a look at the `python3-psutil` APIs and see if we can accomplish the same thing?

Oh very cool, I had no idea psutil could do network things. I will give it a try.
If that works out we also don't need https://github.com/ros/rosdistro/pull/39511

2024-01-11 16:32 UTC, lalten commented
I changed to psutil, it works great and is very compatible to previous behavior. Would be happy about a review @clalancette :)

2024-01-11 20:03 UTC, clalancette approved these changes
This looks great, thanks.  I'm happy to get rid of one additional dependency.  I'll run full CI on this next.

2024-01-11 20:04 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20063)](http://ci.ros2.org/job/ci_linux/20063/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14516)](http://ci.ros2.org/job/ci_linux-aarch64/14516/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20784)](http://ci.ros2.org/job/ci_windows/20784/)

2024-01-12 21:50 UTC, lalten commented
> CI:
> * Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20063)](http://ci.ros2.org/job/ci_linux/20063/)
> * Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14516)](http://ci.ros2.org/job/ci_linux-aarch64/14516/)
> * Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20784)](http://ci.ros2.org/job/ci_windows/20784/)

Looks green! Can this be merged then?

Is it possible to land this in the next Humble patch release as well?

2024-01-12 23:35 UTC, merged

2024-01-12 23:35 UTC, fujitatomoya commented
@lalten thanks for the contribution.

2024-01-13 13:30 UTC, clalancette commented
> Is it possible to land this in the next Humble patch release as well?

I'd like to keep this in Rolling for a while before we do that, to see if any problems come up.

Even so, I actually don't see a compelling reason to do it.  `netifaces` is available in Ubuntu 22.04 (where Humble is supported), and will remain so for the lifetime of the distribution.  So I guess I just don't see the need to make this lateral move and risk regressions.