ros2cli.node.daemon : try getting fdsize from /proc for open fd limit
ros2/ros2cli pull request #888
Opened 2024-03-08 07:53 UTC by akssri-sony

#852 remove inheritence of open fds to fix the issue. It use the soft-limit from RLIMIT_NOFILE to loop over all fds.

This breaks ros2cli on some Unices due to a high soft-limit,
https://github.com/ros2/ros2/issues/1531

This PR follows Ruby's approach of reading ~/proc/self/status~ to get fdsize for the loop-limit (as suggested by @clalancette in the bug-report).

Tested this on the latest osrf/ros:rolling-desktop.

2024-03-08 13:04 UTC, clalancette requested changes

2024-03-08 13:04 UTC, clalancette commented on ros2cli/ros2cli/node/daemon.py
> +        #
I'm going to suggest we do this in a different way, more like this:

```suggestion
        string_to_find = 'FDSize:'
        fdlimit = None
        try:
            # Some unices have a high soft_limit; read fdsize if available.
            with open('/proc/self/status', 'r') as infp:
                for line in infp:
                    if line.startswith(string_to_find):
                        num_only = line[len(string_to_find):].strip()
                        fdlimit = int(num_only)
                        break
        except (FileNotFoundError, ValueError):
            pass

        if fdlimit is None:
            import resource
            fdlimit, _ = resource.getrlimit(resource.RLIMIT_NOFILE)
```

I think this is easier to read, and also ensures that we close the file descriptor when we are done using it.

2024-03-08 14:08 UTC, akssri-sony commented on ros2cli/ros2cli/node/daemon.py
> +        #
fixed.

2024-03-08 14:08 UTC, akssri-sony commented on ros2cli/ros2cli/node/daemon.py
> +                line = next(filter(lambda x: x.startswith(string_to_find), iter(f)))
sg; i've replaced it with a loop

2024-03-08 14:17 UTC, clalancette approved these changes
This looks great, thanks!  I'll run CI on it next.

2024-03-08 14:18 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20446)](http://ci.ros2.org/job/ci_linux/20446/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14848)](http://ci.ros2.org/job/ci_linux-aarch64/14848/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21189)](http://ci.ros2.org/job/ci_windows/21189/)

2024-03-08 16:53 UTC, fujitatomoya approved these changes
makes sense, lgtm

2024-03-09 02:50 UTC, merged

2024-06-03 21:12 UTC, fujitatomoya commented
@Mergifyio backport iron humble