NodeStrategy supports node name argument.
ros2/ros2cli pull request #941
Opened 2024-10-21 15:48 UTC by fujitatomoya

closes https://github.com/ros2/ros2/issues/1614

2024-10-21 21:07 UTC, fujitatomoya reviewed
Since this is not tested yet, i will keep this as draft.

but if you have any objections to have `node_name` argument in `NodeStrategy`, please share your thoughts. I do not really see the downside for this parameter exntension.

2024-10-25 21:19 UTC, fujitatomoya commented
Pulls: ros2/ros2cli#941
Gist: https://gist.githubusercontent.com/fujitatomoya/81fe8695f0df1f4dde75155a6d12ba30/raw/b83bb9f7cc34fe9fd1a22c17bac34b2dfd316e54/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2cli ros2topic
TEST args:  --packages-above ros2cli ros2topic
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14732
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22030)](http://ci.ros2.org/job/ci_linux/22030/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16289)](http://ci.ros2.org/job/ci_linux-aarch64/16289/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1549)](http://ci.ros2.org/job/ci_linux-rhel/1549/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22764)](http://ci.ros2.org/job/ci_windows/22764/)

2024-10-27 18:07 UTC, fujitatomoya commented
@clalancette @ahcorde can you review this? i do not think there is any downside for this.

2024-11-01 13:50 UTC, clalancette requested changes
I think this is fine.  I've left one wording improvement.

2024-11-01 13:50 UTC, clalancette commented on ros2topic/ros2topic/verb/echo.py
> +            help='Name of the created echoing node')
```suggestion
            help='The name of the echoing node; by default, will be a hidden node name')
```

2024-11-06 18:48 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22101)](http://ci.ros2.org/job/ci_linux/22101/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16356)](http://ci.ros2.org/job/ci_linux-aarch64/16356/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1620)](http://ci.ros2.org/job/ci_linux-rhel/1620/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22840)](http://ci.ros2.org/job/ci_windows/22840/)

2024-11-07 18:28 UTC, clalancette approved these changes

2024-11-07 18:35 UTC, fujitatomoya commented
@clalancette thanks for review!

2024-11-07 18:35 UTC, merged